webtalk_init -webtalk_dir /home/ashuvo/amit/github_repo/RTL_design/apb2apb_bridge/run_viv/xsim.dir/apb_bridge_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Dec  2 10:53:17 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2288692" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ef0c5a0b-0d4e-40e1-a9c5-cf2e7fcad1e0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d723a2c1-b029-48ed-a20c-9efa4b1b4fb0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "196" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "RedHatEnterpriseClient" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Red Hat Enterprise Linux Client release 7.6 (Maipo)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1440.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "1645 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "109476_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3022669461 -regid "" -xml /home/ashuvo/amit/github_repo/RTL_design/apb2apb_bridge/run_viv/xsim.dir/apb_bridge_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ashuvo/amit/github_repo/RTL_design/apb2apb_bridge/run_viv/xsim.dir/apb_bridge_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ashuvo/amit/github_repo/RTL_design/apb2apb_bridge/run_viv/xsim.dir/apb_bridge_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
